"""
Suggestion Engine — Proactive AI-powered task suggestions.
Observes user activity via periodic screen captures, analyzes context,
and suggests the most helpful next action with priority levels.
"""

from __future__ import annotations

import asyncio
import logging
import time
from typing import Any, Callable, Dict, List, Optional

from PIL import Image
from pydantic import BaseModel, Field
from rich.console import Console
from rich.panel import Panel

from magnum.config import config
from magnum.intelligence.grounding import ScreenGrounder
from magnum.sentinel.content_analyzer import ContentAnalyzer
from magnum.sentinel.activity_journal import ActivityJournal, ActivityEntry, get_activity_journal

logger = logging.getLogger(__name__)
console = Console()


class Suggestion(BaseModel):
    """A proactive suggestion generated by the engine."""
    suggestion: str = ""
    reason: str = ""
    priority: str = "low"            # critical, high, medium, low
    priority_emoji: str = "🟢"
    category: str = "organization"   # coding, communication, review, break, organization
    timestamp: float = 0.0
    app_context: str = ""


class SuggestionEngine:
    """
    Periodically observes the user's screen and generates proactive suggestions.
    Runs as a background async task alongside the Sentinel.
    """

    def __init__(
        self,
        screenshot_fn: Optional[Callable] = None,
        overlay_fn: Optional[Callable] = None,
        voice_fn: Optional[Callable] = None,
        analyzer: Optional[ContentAnalyzer] = None,
        journal: Optional[ActivityJournal] = None,
    ) -> None:
        self._screenshot_fn = screenshot_fn
        self._overlay_fn = overlay_fn
        self._voice_fn = voice_fn
        self._analyzer = analyzer or ContentAnalyzer()
        self._journal = journal or get_activity_journal()

        # State
        self._suggestions: List[Suggestion] = []
        self._last_suggestion_time: float = 0.0
        self._scan_count = 0
        self._active = False
        self._task: Optional[asyncio.Task] = None
        self._stop_event = asyncio.Event()

        # Timing
        self.suggestion_interval: float = config.suggestion_interval
        self.activity_log_interval: float = config.activity_log_interval

    @property
    def is_active(self) -> bool:
        return self._active

    @property
    def recent_suggestions(self) -> List[Suggestion]:
        return self._suggestions[-5:]

    async def start(self) -> None:
        """Start the background suggestion engine."""
        if self._active:
            return
        self._active = True
        self._stop_event.clear()
        self._task = asyncio.create_task(self._main_loop())
        logger.info("SuggestionEngine started")

    async def stop(self) -> None:
        """Stop the suggestion engine."""
        self._active = False
        self._stop_event.set()
        if self._task and not self._task.done():
            self._task.cancel()
            try:
                await self._task
            except asyncio.CancelledError:
                pass
        logger.info("SuggestionEngine stopped")

    async def suggest_now(self) -> Optional[Suggestion]:
        """Generate an on-demand suggestion (not waiting for the poll interval)."""
        screenshot = await self._take_screenshot()
        if screenshot is None:
            return None
        return await self._generate_suggestion(screenshot)

    async def log_activity_now(self) -> Optional[ActivityEntry]:
        """Log the current activity immediately."""
        screenshot = await self._take_screenshot()
        if screenshot is None:
            return None
        return await self._log_current_activity(screenshot)

    # ── Core Loop ──

    async def _main_loop(self) -> None:
        """Main background loop: log activity + generate suggestions periodically."""
        try:
            while not self._stop_event.is_set():
                self._scan_count += 1

                try:
                    screenshot = await self._take_screenshot()
                    if screenshot:
                        # 1. Log current activity
                        await self._log_current_activity(screenshot)

                        # 2. Generate suggestion if enough time has passed
                        now = time.time()
                        if now - self._last_suggestion_time >= self.suggestion_interval:
                            await self._generate_suggestion(screenshot)
                            self._last_suggestion_time = now

                except Exception as e:
                    logger.warning(f"SuggestionEngine loop error: {e}")

                await asyncio.sleep(self.activity_log_interval)

        except asyncio.CancelledError:
            pass
        finally:
            self._active = False

    async def _take_screenshot(self) -> Optional[Image.Image]:
        """Take a screenshot via the driver."""
        if not self._screenshot_fn:
            return None
        try:
            result = self._screenshot_fn()
            if asyncio.iscoroutine(result):
                return await result
            return result
        except Exception as e:
            logger.warning(f"Screenshot failed: {e}")
            return None

    async def _log_current_activity(self, screenshot: Image.Image) -> Optional[ActivityEntry]:
        """Analyze screen and log current activity to journal."""
        try:
            elements = ScreenGrounder.extract_screen_text_elements(screenshot)
            ocr_text = " ".join(el.text.strip() for el in elements if el.text.strip())

            if not ocr_text or len(ocr_text) < 20:
                return None

            # Detect foreground app from first OCR elements (menu bar)
            app_name = ""
            for el in elements[:5]:
                text = el.text.strip()
                for known_app in (
                    "Antigravity", "Google Chrome", "Safari", "Terminal",
                    "Visual Studio Code", "VS Code", "Slack", "Discord",
                    "Finder", "Notes", "Mail", "WhatsApp", "Spotify",
                    "Xcode", "iTerm", "Messages",
                ):
                    if known_app.lower() in text.lower():
                        app_name = known_app
                        break
                if app_name:
                    break

            # AI activity analysis
            analysis = await asyncio.to_thread(
                self._analyzer.analyze_activity,
                ocr_text,
                app_name,
            )

            entry = ActivityEntry(
                app_name=analysis.get("app_name", app_name) or app_name,
                activity_summary=analysis.get("activity_summary", "Working"),
                importance=analysis.get("importance", "medium"),
                importance_score=int(analysis.get("importance_score", 5)),
                context=analysis.get("context", ""),
                suggested_next=analysis.get("suggested_next", ""),
                screen_text_preview=ocr_text[:200],
            )

            self._journal.log_activity(entry)
            return entry

        except Exception as e:
            logger.warning(f"Activity logging failed: {e}")
            return None

    async def _generate_suggestion(self, screenshot: Image.Image) -> Optional[Suggestion]:
        """Generate a proactive suggestion based on current screen + activity history."""
        try:
            elements = ScreenGrounder.extract_screen_text_elements(screenshot)
            ocr_text = " ".join(el.text.strip() for el in elements if el.text.strip())

            if not ocr_text or len(ocr_text) < 20:
                return None

            # Detect current app
            app_name = ""
            for el in elements[:5]:
                for known_app in (
                    "Antigravity", "Google Chrome", "Terminal", "VS Code",
                    "Slack", "Discord", "Mail", "WhatsApp",
                ):
                    if known_app.lower() in el.text.strip().lower():
                        app_name = known_app
                        break
                if app_name:
                    break

            # Get activity log context
            activity_log = self._journal.get_journal_text(hours=2, max_entries=20)

            # AI suggestion
            result = await asyncio.to_thread(
                self._analyzer.generate_suggestion,
                activity_log,
                ocr_text,
                app_name,
            )

            suggestion = Suggestion(
                suggestion=result.get("suggestion", "Continue your current task"),
                reason=result.get("reason", ""),
                priority=result.get("priority", "low"),
                priority_emoji=result.get("priority_emoji", "🟢"),
                category=result.get("category", "organization"),
                timestamp=time.time(),
                app_context=app_name,
            )

            self._suggestions.append(suggestion)
            if len(self._suggestions) > 20:
                self._suggestions = self._suggestions[-20:]

            # Display suggestion
            self._display_suggestion(suggestion)

            return suggestion

        except Exception as e:
            logger.warning(f"Suggestion generation failed: {e}")
            return None

    def _display_suggestion(self, suggestion: Suggestion) -> None:
        """Display suggestion via overlay and console."""
        console.print(Panel(
            f"[bold white]{suggestion.priority_emoji} {suggestion.suggestion}[/bold white]\n"
            f"[dim]{suggestion.reason}[/dim]",
            title=f"[bold cyan]💡 Suggestion ({suggestion.priority.upper()})[/bold cyan]",
            border_style="cyan",
        ))

        # Voice for high/critical priority
        if suggestion.priority in ("critical", "high") and self._voice_fn:
            try:
                self._voice_fn(f"Suggestion: {suggestion.suggestion}")
            except Exception:
                pass

        # Overlay toast
        if self._overlay_fn:
            try:
                self._overlay_fn("suggestion", {
                    "text": suggestion.suggestion,
                    "priority": suggestion.priority,
                    "emoji": suggestion.priority_emoji,
                })
            except Exception:
                pass
